// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTWIqWN71CjurBdHYiagdFpZfpMi5Xr0',
    appId: '1:543143943897:web:f76952e282e8d7f8d868c8',
    messagingSenderId: '543143943897',
    projectId: 'dereruministic',
    authDomain: 'dereruministic.firebaseapp.com',
    storageBucket: 'dereruministic.firebasestorage.app',
    measurementId: 'G-01YSL0Z0DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8q9D2nDXryt4O2DA9K41WRZHpJn5m7dk',
    appId: '1:543143943897:android:c787bd926cb8c50fd868c8',
    messagingSenderId: '543143943897',
    projectId: 'dereruministic',
    storageBucket: 'dereruministic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXeIkj5QFV4u_kNaWtHdfxNLk-2J9I1M',
    appId: '1:543143943897:ios:00713fd79c1d6415d868c8',
    messagingSenderId: '543143943897',
    projectId: 'dereruministic',
    storageBucket: 'dereruministic.firebasestorage.app',
    iosBundleId: 'com.example.dereruministic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXeIkj5QFV4u_kNaWtHdfxNLk-2J9I1M',
    appId: '1:543143943897:ios:00713fd79c1d6415d868c8',
    messagingSenderId: '543143943897',
    projectId: 'dereruministic',
    storageBucket: 'dereruministic.firebasestorage.app',
    iosBundleId: 'com.example.dereruministic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuTWIqWN71CjurBdHYiagdFpZfpMi5Xr0',
    appId: '1:543143943897:web:5e568bf02315d104d868c8',
    messagingSenderId: '543143943897',
    projectId: 'dereruministic',
    authDomain: 'dereruministic.firebaseapp.com',
    storageBucket: 'dereruministic.firebasestorage.app',
    measurementId: 'G-JR24YM7KBV',
  );
}
